from pathlib import Path
import json,hashlib,datetime,re,subprocess
R=Path(__file__).resolve().parent
OLD=Path('/home/denis/.local/state/claude-dispatcher/recovery-20261004')
NEW=Path('/home/denis/.local/state/claude-dispatcher/recovery-20261005')
SITE='/home/denis/projects/marzhavbetone.ru'
STAMP=datetime.datetime.now(datetime.timezone.utc).isoformat()
S=R/'input-snapshots';S.mkdir(exist_ok=True)
manifest=[];data={}
PRIOR={x['id']:x for x in json.loads((R/'freeze-20261005-1715/input-manifest.json').read_text())['inputs']}
def load(key,path,fields=None):
    path=Path(path);prior=PRIOR.get(key);readpath=Path(prior['exact_snapshot']) if prior and prior.get('exact_snapshot') else path;raw=readpath.read_bytes();value=json.loads(raw)
    if prior:assert hashlib.sha256(raw).hexdigest()==prior['sha256'],(key,'PRIOR_PIN_CHANGED')
    assert isinstance(value,dict),(key,'JSON_OBJECT_REQUIRED')
    digest=hashlib.sha256(raw).hexdigest()
    if len(raw)<=65536:
        name=key+'-'+digest[:12]+'.json';(S/name).write_bytes(raw);snapshot=str(S/name)
    else:snapshot=None
    manifest.append({'id':key,'path':str(path),'sha256':digest,'bytes':len(raw),'exact_snapshot':snapshot,'consumed_fields':fields or 'structured receipt fields','large_raw_fields_excluded':len(raw)>65536})
    data[key]=value;return value
h=load('handoff',OLD/'handoff-20261005-parallel-verified.json')
f=load('s1-full6077',NEW/'mechanical/s1-final-verification/final-proof.json')
a=load('s1-composition-a774',OLD/'s1-multipage-print-instructions-20261005/actual-merged-composition.json')
n=load('s1-narrow-header',OLD/'s1-multipage-print-instructions-20261005/receipt.json')
v=load('s1-header-visual',OLD/'s1-multipage-print-instructions-20261005/root-visual-receipt.json')
c=load('s1-citation-review',OLD/'s1-legal-inventory-independent-20261005-2315/independent-review-receipt.json')
i=load('s1-citation-extraction',OLD/'s1-current-citation-inventory-20261005/verification-receipt.json')
z=load('s1-citation-freeze',OLD/'s1-current-citation-inventory-20261005/freeze-receipt.json')
m=load('s1-citation-merged-composition',OLD/'s1-current-citation-inventory-20261005/pr479-actual-composition-receipt.json')
p2=load('p2-actual-php',OLD/'next-packaging-qa-20261005/p2/receipt.json',['status','source_sha','count','archive_sha256','member_hashes','crc_failure_member','source_immutable','boundary'])
p2c=load('p2-composition476',OLD/'next-packaging-qa-20261005/pr476-actual-composition-receipt.json',['merged_working_sha','buyer_baseline_sha','buyer_config_generator_exact_unchanged','all9_report_evidence_blobs_equal_accepted','status'])
p2m=load('p2-merge476',OLD/'next-packaging-qa-20261005/pr476-actual-merged-receipt.json')
p3=load('p3-actual-php',NEW/'mechanical/p3-actual-zip-302d/receipt.json')
p3c=load('p3-composition478',NEW/'mechanical/p3-actual-zip-302d/actual-merged-composition-478.json')
p3tests=load('p3-producer35',OLD/'p3-actual-merged-verification-20261005-2043.json')
p3q=load('p3-citation-current-independent',OLD/'p3-citation-inventory-independent-20261005/independent-review-receipt.json')
p3ready=load('p3-citation-refined-ready',NEW/'mechanical/p3-current-citation-inventory-20261005/READY.json')
p3inv=load('p3-citation-refined-verification',NEW/'mechanical/p3-current-citation-inventory-20261005/verification-receipt.json')
p3delta=load('p3-citation-numeric-delta',NEW/'mechanical/p3-current-citation-inventory-20261005/numeric-coverage-delta.json')
p5=load('p5-actual-php',OLD/'p5-actual-php-zip-20261005/receipt.json')
p5c=load('p5-composition474',OLD/'p5-actual-php-zip-20261005/actual-merged-composition-474.json')
p5tests=load('p5-native16',OLD/'p5-actual-merged-verification-20261005-2040.json')
p5q=load('p5-citation-independent',OLD/'p5-citation-inventory-independent-20261005/independent-review-receipt.json')
p5ready=load('p5-citation-ready',OLD/'p5-current-citation-inventory-20261005/READY.json')
p5inv=load('p5-citation-extraction',OLD/'p5-current-citation-inventory-20261005/verification-receipt.json')
p5pr=load('p5-citation-draft480',OLD/'p5-current-citation-inventory-20261005/documentary-pr.json')
p5new=load('p5-citation-composition480',OLD/'p5-current-citation-inventory-20261005/actual-merged-composition-480.json')
coord=load('coordinator-recent-observations',R/'coordinator-observations.json')
contracts=json.loads((R/'contract-inputs.json').read_text())
for k,item in enumerate(contracts):manifest.append({'id':'contract-'+str(k),'path':item['path'],'sha256':item['sha256'],'repo_head':item['repo_head'],'consumed_fields':'full contract; runtime copy identical'})
# Existing documentary records only; no product/norm/source verification is run.
record_path='tools/templates/s1-reviewed-corrections/corrections.json'
raw=subprocess.check_output(['git','-C',SITE,'show',a['actual_working_head']+':'+record_path]);owner=json.loads(raw)
(S/'s1-reviewed-corrections-record.json').write_bytes(raw);manifest.append({'id':'s1-excel-lineage-record','git_source_sha':a['actual_working_head'],'path':record_path,'sha256':hashlib.sha256(raw).hexdigest(),'exact_snapshot':str(S/'s1-reviewed-corrections-record.json')})
stop_path='tools/candidates/MB001_R2_P2_FORMS_R3.md';raw=subprocess.check_output(['git','-C',SITE,'show',p2c['merged_working_sha']+':'+stop_path]);text=raw.decode();assert all('STOP-P2-R3-'+str(x) in text for x in [1,2,3])
manifest.append({'id':'p2-existing-stop-report','git_source_sha':p2c['merged_working_sha'],'path':stop_path,'sha256':hashlib.sha256(raw).hexdigest(),'consumed_fields':'existing STOP-P2-R3-1/2/3; no body reinterpretation'})
common=[{'gate':'official_normative_currentness','status':'NOT_VERIFIED','input':'handoff','note':'Factual citation inventory/technical receipts do not close this gate.'},{'gate':'human_legal_acceptance','status':'NOT_PERFORMED','input':'handoff'},{'gate':'release_owner_main_deploy_live_price_SKU_payment','status':'OPEN_NOT_AUTHORIZED_BY_TECHNICAL_ACCEPTANCE','input':'handoff'}]
excel=[]
for name,r in owner.items():
    excel.append({'file':name,'original_owner_sha256':r['owner_sha256'],'reviewed_correction_sha256':r['correction_sha256'],'independent_exact_correction_review':r['independent_review'],'owner_approval_of_new_text':r['owner_approval_of_new_text'],'review_report_sha256':r['review_report_sha256'],'input':'s1-excel-lineage-record'})
modules=[
 {'module':'S1','working_head':m['actual_merged_sha'],'buyer_snapshot_sha':a['actual_working_head'],'technical':{'status':'ACCEPTED_SCOPED_INTEGRATION_COMPOSITION','full105_and_two_complete_builds_source_sha':f['actual_working_head'],'full_suite_on_current_head':False,'new_paragraph_checks':n['tests'],'new_doc03_sha256':a['doc03_sha256'],'composition_unchanged_paths':len(a['unchanged6077_bytes']),'header_visual_changed_pages':v['changed_pages_root_seen'],'inputs':['s1-full6077','s1-composition-a774','s1-narrow-header','s1-header-visual']},'citation':{'status':'ACCEPTED_FACTUAL_INVENTORY_MERGED','source_sha':c['source_sha'],'output_sha':m['accepted_output_sha'],'working_merge_sha':m['actual_merged_sha'],'pr':479,'inventory_sha256':c['inventory_sha256'],'occurrences':c['literal_occurrences_checked'],'groups_not_norms':c['dedup_groups_checked'],'unresolved_markers_not_defects':c['unresolved_markers_checked'],'checks':c['checks'],'errors':len(c['errors']),'inputs':['s1-citation-review','s1-citation-extraction','s1-citation-merged-composition']},'excel_lineage':excel,'remaining_gates':common+[{'gate':'owner_excel_acceptance_of_new02_08_text','status':'PENDING','input':'s1-excel-lineage-record'},{'gate':'registry_bound_normative_verdict','status':c['normative_verdict'],'input':'s1-citation-review'}]},
 {'module':'P2','working_head':p2c['merged_working_sha'],'buyer_snapshot_sha':p2['source_sha'],'technical':{'status':p2['status'],'PHP_members':p2['count'],'zip_sha256':p2['archive_sha256'],'CRC_failure_member':p2['crc_failure_member'],'buyer_config_generator_unchanged':p2c['buyer_config_generator_exact_unchanged'],'pr':476,'inputs':['p2-actual-php','p2-composition476','p2-merge476']},'citation':{'status':'NO_CURRENT_AUTHOR_RECEIPT_INCLUDED','executor_state':'START_OBSERVED_BY_COORDINATOR_RESULT_RECEIPT_PENDING','coordinator_observed_pid':coord['P2']['observed_pid'],'executor_running_now':'NOT_CLAIMED','input':'coordinator-recent-observations','source_sha':p2c['merged_working_sha']},'remaining_gates':common+[{'gate':'STOP-P2-R3-1','file':'02-soglasovanie-obema.docx','status':'OPEN','input':'p2-existing-stop-report'},{'gate':'STOP-P2-R3-2','file':'04-akt-skrytyh-rabot.docx','status':'OPEN','input':'p2-existing-stop-report'},{'gate':'STOP-P2-R3-3','file':'05-izmenenie-srokov.docx','status':'OPEN','input':'p2-existing-stop-report'},{'gate':'citation_inventory_current_scope','status':'NO_CURRENT_RECEIPT_INCLUDED'}]},
 {'module':'P3','working_head':p3c['actual_working_head'],'buyer_snapshot_sha':p3['frozen_input_sha'],'technical':{'status':p3['status'],'PHP_members':p3['zip']['members'],'zip_sha256':p3['zip']['sha256'],'zip_bytes':p3['zip']['bytes'],'all15_input_blobs_exact':len(p3c['all15_input_blobs_exact']),'all27_documentary_paths_exact':p3c['all27_documentary_paths_exact'],'metadata02_06':'Microsoft Excel / AppVersion3.1 exact; producer35 narrow receipt inherited','pr':478,'inputs':['p3-actual-php','p3-composition478','p3-producer35']},'citation':{'status':'ACCEPTED_FACTUAL_INVENTORY_DOCUMENTARY_PERSISTENCE_PENDING','source_sha':p3ready['source_sha'],'inventory_sha256':p3ready['citation_map_sha256'],'literal_occurrences':p3inv['literal_occurrences'],'groups_not_norms':p3inv['groups_not_norms'],'unresolved_markers_not_defects':p3inv['unresolved_markers_not_defects'],'numeric_reference_markers':p3inv['numeric_reference_markers'],'prior_rejected_map_sha256':p3delta['rejected_map_sha256'],'current_independent_status':p3q['status'],'independent_checks':p3q['checks'],'independent_errors':len(p3q['errors']),'inputs':['p3-citation-current-independent','p3-citation-refined-ready','p3-citation-refined-verification','p3-citation-numeric-delta']},'remaining_gates':common+[{'gate':'accepted_factual_inventory_documentary_persistence','status':'PENDING','input':'p3-citation-refined-ready'},{'gate':'modulewide_financial_legal_acceptance','status':'NOT_ESTABLISHED_BY_INCLUDED_PACKAGING_PROOF','input':'p3-actual-php'}]},
 {'module':'P5','working_head':p5new['actual_merge_sha'],'buyer_snapshot_sha':p5['source_sha'],'technical':{'status':p5['status'],'PHP_members':p5['member_count'],'zip_sha256':p5['zip_sha256'],'zip_bytes':p5['zip_bytes'],'native04_05_exact':p5['native04_05_exact'],'native04_sha256':p5['all_exact_source_inputs_sha256']['products-storage/07-uderzhaniya-shtrafy-zachety/04-raschet-ubytkov.xlsx'],'native05_sha256':p5['all_exact_source_inputs_sha256']['products-storage/07-uderzhaniya-shtrafy-zachety/05-reestr-uderzhaniy.xlsx'],'native_helper16_scope':'inherited accepted narrow native guard/temp cleanup checks; no rerun','pr':474,'inputs':['p5-actual-php','p5-composition474','p5-native16']},'citation':{'status':'ACCEPTED_FACTUAL_INVENTORY_MERGED','source_sha':p5q['source_sha'],'output_sha':p5pr['head_sha'],'working_merge_sha':p5new['actual_merge_sha'],'pr':480,'inventory_sha256':p5q['inventory_sha256'],'occurrences':p5q['literal_occurrences_checked'],'groups_not_norms':p5q['dedup_groups_checked'],'unresolved_markers_not_defects':p5q['unresolved_markers_checked'],'checks':p5q['checks'],'errors':len(p5q['errors']),'inputs':['p5-citation-independent','p5-citation-ready','p5-citation-extraction','p5-citation-draft480','p5-citation-composition480']},'remaining_gates':common+[{'gate':'modulewide_financial_legal_acceptance','status':'NOT_ESTABLISHED_BY_INCLUDED_PACKAGING_NATIVE_PROOF','input':'p5-actual-php'}]}
]
p2q=load('p2-citation-independent',OLD/'p2-citation-inventory-independent-20261005/independent-review-receipt.json')
p2supp=load('p2-citation-independent-supplement',OLD/'p2-citation-inventory-independent-20261005/independent-supplemental-scope-receipt.json')
p2ready=load('p2-citation-ready',OLD/'p2-current-citation-inventory-20261005-recovery/READY.json')
p2inv=load('p2-citation-extraction',OLD/'p2-current-citation-inventory-20261005-recovery/verification-receipt.json')
p3pr=load('p3-citation-draft481',NEW/'mechanical/p3-current-citation-inventory-20261005/draft-pr.json')
assert p2q['status']=='ACCEPT_FACTUAL_INVENTORY' and not p2q['errors'] and not p2q['supplemental_errors']
assert p2q['inventory_sha256']==p2ready['citation_map_sha256']==p2inv['map_sha256']
modules[1]['citation']={'status':'ACCEPTED_FACTUAL_INVENTORY_DOCUMENTARY_PERSISTENCE_PENDING','source_sha':p2q['source_sha'],'inventory_sha256':p2q['inventory_sha256'],'occurrences':p2q['literal_occurrences_checked'],'groups_not_norms':p2q['dedup_groups_checked'],'unresolved_markers_not_defects':p2q['unresolved_markers_checked'],'checks_base':p2q['checks'],'checks_supplemental':p2q['supplemental_checks'],'checks_total':p2q['checks']+p2q['supplemental_checks'],'errors':0,'native_text_units':p2q['total_independent_native_text_units'],'PDFs':len(p2q['pdfs']),'PDF_physical_pages':sum(x['physical_pages'] for x in p2q['pdfs']),'PDF_scope_limitation':'Text layer only; images and visual reading order not independently examined','inputs':['p2-citation-independent','p2-citation-independent-supplement','p2-citation-ready','p2-citation-extraction']}
modules[1]['remaining_gates'][-1]={'gate':'accepted_factual_inventory_documentary_persistence','status':'PENDING','input':'p2-citation-independent'}
modules[2]['citation'].update({'pr':481,'draft_head_sha':p3pr['head_sha'],'draft_base_sha':p3pr['base_sha'],'draft_url':p3pr['url'],'actual_merge_status':'PENDING','inputs':modules[2]['citation']['inputs']+['p3-citation-draft481']})
p3merged=load('p3-citation-composition481',NEW/'mechanical/p3-current-citation-inventory-20261005/actual-merged-composition-481.json')
assert p3merged['status']=='VERIFIED_ACTUAL_MERGED_FACTUAL_INVENTORY_COMPOSITION' and p3merged['accepted_map_sha256']==p3q['inventory_sha256']
modules[2]['working_head']=p3merged['actual_working_head']
modules[2]['citation'].update({'status':'ACCEPTED_FACTUAL_INVENTORY_MERGED','working_merge_sha':p3merged['actual_working_head'],'actual_merge_status':'MERGED_VERIFIED','documentary_inputs_exact':len(p3merged['all46_documentary_paths_exact_source_commit']),'inputs':modules[2]['citation']['inputs']+['p3-citation-composition481']})
modules[2]['remaining_gates']=[g for g in modules[2]['remaining_gates'] if g['gate']!='accepted_factual_inventory_documentary_persistence']
p2merged=load('p2-citation-composition482',OLD/'p2-current-citation-inventory-20261005-recovery/pr482-actual-composition-receipt.json')
p2metadata=load('p2-citation-merge482',OLD/'p2-current-citation-inventory-20261005-recovery/pr482-actual-merged-receipt.json')
assert p2merged['status']=='PASS_ACTUAL_WORKING_COMPOSITION' and p2merged['accepted_input_sha']==p2q['source_sha'] and p2merged['original_buyer_sha']==p2['source_sha']
assert p2merged['all15_buyerbytes_unchanged'] and p2merged['all50_documentary_blobs_exact_accepted']
modules[1]['working_head']=p2merged['actual_merged_sha']
modules[1]['citation'].update({'status':'ACCEPTED_FACTUAL_INVENTORY_MERGED','pr':482,'output_sha':p2merged['accepted_output_sha'],'working_merge_sha':p2merged['actual_merged_sha'],'documentary_files_exact':p2merged['proof_files_verified'],'manifest_entries_exact':p2merged['SHA256SUMS_entries_verified'],'inputs':modules[1]['citation']['inputs']+['p2-citation-composition482','p2-citation-merge482']})
modules[1]['remaining_gates']=[g for g in modules[1]['remaining_gates'] if g['gate']!='accepted_factual_inventory_documentary_persistence']
prior_hashes={x['id']:x['sha256'] for x in PRIOR.values()}
assert all(x['sha256']==prior_hashes[x['id']] for x in manifest if x['id'] in prior_hashes),'PRIOR_INPUT_PIN_CHANGED'
assert p3q['status']=='ACCEPT_FACTUAL_INVENTORY' and p3q['inventory_sha256']==p3ready['citation_map_sha256'] and not p3q['errors']
assert p5new['status']=='PASS_ACTUAL_MERGED_FACTUAL_INVENTORY_COMPOSITION' and p5new['source_head']==p5pr['head_sha']
assert [x['module'] for x in modules]==['S1','P2','P3','P5']
for module in modules:
    for field in ['working_head','buyer_snapshot_sha']:assert re.fullmatch('[0-9a-f]{40}',module[field]),(module['module'],field)
    assert module['remaining_gates'] and not any(g['status']=='PASS' for g in module['remaining_gates'])
    assert all(not item['owner_approval_of_new_text'] for item in module.get('excel_lineage',[]))
excluded=[{'kind':'P2full_source_units','sha256':p2ready['full_source_units_sha256'],'path':str(OLD/'p2-current-citation-inventory-20261005-recovery/source-text-units.json'),'reason':'full raw units excluded; READY pins hash'},{'kind':'S1full_source_units','receipt':'s1-citation-freeze',**z['server_only_intermediate']},{'kind':'P3full_source_units','sha256':p3ready['full_source_units_sha256'],'path':str(NEW/'mechanical/p3-current-citation-inventory-20261005/source-text-units.json'),'reason':'large raw units excluded; READY receipt pins hash'},{'kind':'P5full_source_units','receipt':'p5-citation-extraction','details':p5inv.get('server_only_large_unit_manifest'),'reason':'large raw units excluded'},{'kind':'raw_API_bodies','input':'p2-actual-php','field':'commands[].stdout','reason':'large historical PR/user/body metadata excluded from matrix; original receipt hash retained'},{'kind':'buyer_DOCX_XLSX_PDF_ZIP','reason':'not recopied/extracted/retested; accepted receipts provide byte/hash lineage'},{'kind':'S1full_build_outputs','path':str(NEW/'mechanical/s1-final-verification'),'reason':'server-only build-1/build-2; original receipt/manifest authority; no rerun'}]
result={'status':'FACTUAL_MATRIX_DRAFT_FOR_ROOT_REVIEW','observed_utc':STAMP,'execution_pattern':'iterative','primary_result':'factual remaining gates per current exact module','remaining_scope_unknown_for_other_products':True,'catalog_scope_note':'Four accepted technical modules only. Other free/source/legacy/bundle/configured SKU scopes require separate catalog inventory; directory counts establish neither SKU membership nor readiness.','collector_calls':{'model':0,'tests':0,'product_builds':0,'normative_source_checks':0,'merge_deploy':0},'interpretation':'Implementation/accepted scope/working merge/release are distinct; unresolved markers are not automatically defects or confirmed norms. No legal guidance/verdict is created.','modules':modules,'excluded_large_units':excluded,'input_manifest':'input-manifest.json','checkpoint_policy':'verified_only','next':'Refresh only when exact accepted review/merge receipts arrive; root review before documentary commit/push.'}
(R/'completion-gates-matrix.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');(R/'input-manifest.json').write_text(json.dumps({'observed_utc':STAMP,'inputs':manifest,'excluded_large_units':excluded},ensure_ascii=False,indent=2)+'\n')
lines=['# Фактическая готовность S1 / P2 / P3 / P5','',f'Снимок: {STAMP}. Это сборка существующих доказательств; новые тесты, модели, сборки и нормативная сверка не запускались.','','| Модуль | Что технически принято | Карта цитат | Что остаётся открытым |','|---|---|---|---|','| S1 | 105 PASS и две полные сборки — только база 6077; новая фраза 03: 2 PASS, две f03 сборки, визуальная приёмка и точная композиция a774. | 479 слит; 47 упоминаний/24 группы/23 unresolved markers; 1178 проверок без ошибок. | Новый текст 02/08 ещё не принят владельцем в Excel; нормативная текущесть/человек/release gate. |','| P2 | Реальный PHP ZIP: 15 файлов; buyer/config/generator сохранены; 476 слит. | Принята фактическая карта: 155 проверок (137 + 18) без ошибок; 450 текстовых единиц, 15 файлов, 3 PDF / 6 страниц. PR482 слит; 50 документальных файлов и 48 записей manifest точны. | STOP форм 02/04/05; нормативная текущесть/человек/release gate. |','| P3 | Реальный PHP ZIP: 11 файлов; 15 входов/27 доказательств точны; 478 слит. | Исправленная карта принята: 396 проверок без ошибок, 15 упоминаний/2 группы/34 markers; PR481 слит; 46 documentary paths / 44 manifest entries / 14 QA files точны. | Полнота финансовой/юридической приёмки не доказана упаковкой; currentness/человек/release. |','| P5 | Реальный PHP ZIP: 11 файлов; owner-native 04/05 сохранены; 474 слит. | 492 проверки без ошибок; 480 слит, 17 входов/30 proof paths точны. | Финансовая/юридическая приёмка модуля не доказана native/ZIP scope; currentness/человек/release. |','','Точные SHA текущих рабочих снимков:','']
for x in modules:lines += [f"- {x['module']}: `{x['working_head']}`; проверенные buyer bytes: `{x['buyer_snapshot_sha']}`."]
lines += ['','S1 Excel: исходные owner-native 02/08 и их approved hashes сохранены. Новые 02/08 — отдельно принятые предметным проверяющим correction bytes; это не новая owner Excel-приёмка и не human legal acceptance. Файл 04 остаётся исходным native. P5 exact native 04/05 не означает приёмки всех финансовых конструкций модуля.','','Во всех четырёх строках currentness NOT_VERIFIED, human legal NOT_PERFORMED и release-owner gate открыты. SALE_READY не заявлен; рабочее слияние не равно публикации/оплате/выдаче. Неопределённые маркеры не считаются автоматически дефектами.','','Все прочие продукты: remaining_scope_unknown_for_other_products=true. Эти четыре строки не означают готовность всего каталога; отдельный catalog membership/product-role inventory выполняется другим исполнителем.','','Полные source units, buyer binaries, сырые API bodies и полные server-only build directories исключены из этого небольшого отчёта явно; их происхождение/хэши перечислены в input-manifest.json. Все утверждения JSON ссылаются на input IDs.','']
(R/'completion-gates-matrix.md').write_text('\n'.join(lines))
(R/'validation-receipt.json').write_text(json.dumps({'status':'VERIFIED_FACTUAL_SNAPSHOT_PENDING_ROOT_REVIEW','four_modules_exact':True,'all_module_heads_full40SHA':True,'no_owner_newtext_upgrade':True,'no_sale_ready':True,'no_tests_models_builds_sourcechecks':True,'input_count':len(manifest),'output_sha256':{n:hashlib.sha256((R/n).read_bytes()).hexdigest() for n in ['completion-gates-matrix.json','completion-gates-matrix.md','input-manifest.json']}},indent=2)+'\n')
print('MATRIX_READY',len(manifest),'INPUTS',len(modules),'MODULES','JSON_BYTES',(R/'completion-gates-matrix.json').stat().st_size,'MD_BYTES',(R/'completion-gates-matrix.md').stat().st_size)
