import json,pathlib,zipfile,hashlib,xml.etree.ElementTree as E,re,fitz,datetime
from PIL import Image
R=pathlib.Path('/workspace/scratch/f25d74acc3f7');O=R/'p13-checkbox-rootcause-20261006';I=R/'daywork-next-queue-20261006/p13';P=json.loads((I/'passport.json').read_text());src=pathlib.Path(P['required_inputs'][0]['local_path']);pdf=next(I.glob('*.pdf'));N={'w':'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
bind=[{'path':str(x),'sha256':sha(x)}for x in [src,pdf,I/'page-1.png',I/'glyph-diagnostic.json',R/'mb001-daywork/tools/candidates/evidence/FINAL_FACTUAL_MATRIX_AND_BASELINE_20261005/catalog-baseline/canonical-contracts/Task_Setting_Protocol.md']]
with zipfile.ZipFile(src)as z:
 ps=E.fromstring(z.read('word/document.xml')).findall('.//w:p',N);samples=[]
 for k in [16,17,18,19]:
  p=ps[k];samples.append({'locator':f'word/document.xml/paragraph:{k}','xml':E.tostring(p,encoding='unicode'),'text':''.join(v.text or ''for v in p.findall('.//w:t',N)),'rPr_count':len(p.findall('.//w:rPr',N)),'pPr_count':len(p.findall('.//w:pPr',N)),'bookmarks_hyperlinks_lists':sum(len(p.findall('.//w:'+n,N))for n in ['bookmarkStart','hyperlink','numPr'])})
 st=E.fromstring(z.read('word/styles.xml'));default=E.tostring(st.find('w:docDefaults',N),encoding='unicode');normal=E.tostring(next(x for x in st.findall('w:style',N)if x.attrib.get('{'+N['w']+'}styleId')=='Normal'),encoding='unicode');sourcecount=sum(s['text'].count('☐')for p in ps for s in [{'text':''.join(v.text or ''for v in p.findall('.//w:t',N))}])
f=fitz.open(pdf);trace=[];counts=[]
for pn,page in enumerate(f):
 cs=[]
 for s in page.get_texttrace():
  t=''.join(chr(v[0])for v in s['chars'])
  for c in s['chars']:
   if c[0]==0x2610:cs.append({'font':s['font'],'origin':list(c[2]),'glyph_id':c[1]})
  if pn==0 and 625<s['bbox'][1]<710:trace.append({k:s[k] for k in ['font','bbox','type','seqno']}|{'text':t,'chars':[{'unicode':c[0],'glyph_id':c[1],'origin':list(c[2]),'bbox':list(c[3])}for c in s['chars']]})
 counts.append({'page':pn+1,'checkbox_count':len(cs),'first_two':cs[:2]})
cmaps=[]
for x in [180,170]:
 obj=f.xref_object(x);m=re.search(r'/ToUnicode (\d+) 0 R',obj);cmap=f.xref_stream(int(m[1])).decode('latin1');cmaps.append({'font_xref':x,'font_object':obj,'to_unicode':cmap,'maps_U2610':'<2610>'in cmap})
drawings=[{'type':d['type'],'rect':list(d['rect'])}for d in f[0].get_drawings()if d['rect'].intersects(fitz.Rect(85,625,115,647))]
img=Image.open(I/'page-1.png');sx=img.width/f[0].rect.width;sy=img.height/f[0].rect.height;crop=img.crop((int(84*sx),int(624*sy),int(515*sx),int(711*sy)));crop.save(O/'missing-vs-neighbor.png');crop.verify() if False else None
facts={'observed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'inputs':bind,'source_paragraph_comparison':samples,'default_style':default,'normal_style':normal,'pdf_first_and_neighbor_lines':trace,'checkbox_counts':{'source':sourcecount,'pdf':sum(v['checkbox_count']for v in counts),'per_page':counts},'pdf_fonts_and_tounicode':cmaps,'first_checkbox_expected_region_drawings':drawings,'source_before_after_equal':sha(src)==bind[0]['sha256'],'pdf_before_after_equal':sha(pdf)==bind[1]['sha256'],'no_source_write_no_rerender':True}
(O/'facts.json').write_text(json.dumps(facts,ensure_ascii=False,indent=2)+'\n')
result={'classification':'LOCAL_DOCX_TO_PDF_FONT_FALLBACK_EXPORT_GLYPH_LOSS','observed_fact':['Four compared source checkbox paragraphs share exact no-rPr/no-pPr structure; no bookmarks, hyperlinks or lists override the affected run','First affected PDF line uses Caladea-Regular punctuation/spacing and NotoSerif-Regular Cyrillic; next checkbox lines use DejaVuSans for checkbox and Cyrillic','First line has no U2610 PDF texttrace glyph and no vector drawing at expected checkbox region; neighbors have DejaVuSans glyph17 U2610 at x90.1','First Cyrillic Б appears at x90.1 where neighbors place checkbox, following ы at x104.741; visible displacement supports export/shaping loss rather than pdftotext-only extraction','NotoSerif subset ToUnicode contains no U2610; DejaVuSans subset contains U2610 mapping <11>','Source checkbox count='+str(sourcecount)+'; actual PDF mapped checkbox count='+str(sum(v['checkbox_count']for v in counts))], 'root_cause':'UNRESOLVED_EXACT_MECHANISM','inference':'Loss occurs upstream of PDF extraction in the local font fallback/shaping/export path; source paragraph formatting mismatch, clipping or a merely wrong extraction map is unsupported by retained facts','hypotheses':['First occurrence fallback initialization/segmentation may pick a run font without the checkbox glyph','PDF export glyph stream may omit the first unsupported font fallback symbol'], 'not_proven':['Which LibreOffice component caused loss','Reproducibility on server LibreOffice24.2 or native Word','Whether concurrency affected shared global font cache'],'minimal_next_candidate':{'scope':'Only a disposable copy of source paragraph16 first checkbox glyph in separate run with explicit DejaVu Sans rFonts; all following text/style/source unchanged','reason':'Same retained PDF successfully embeds/renders U2610 from DejaVuSans for adjacent identical source paragraphs','not_executed':True,'required_validation':['Compare original/candidate DOCX runs and confirm only checkbox font declaration changed','One bounded candidate render under explicit new test hypothesis, no retries','Strict U2610-aware normalized text match all93 units','Source62 PDF62 checkbox count; check affected control glyph/Б word placement visually','No native Word/server compatibility claim without those renders']},'negative_gate':{'normalization':'Whitespace and soft hyphen only; never remove U2610 or replace it with generic square','test_cases':['Original source paragraph16 vs retained PDF must FAIL','Neighbors paragraph17/18 must PASS','Fixture losing checkbox with all words identical must FAIL','Fixture correct checkbox and whitespace differences must PASS']},'status':'CAUSAL_BOUNDARY_NARROWED_EXACT_ROOT_CAUSE_UNRESOLVED'}
(O/'result.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');passport={'task_id':'p13-checkbox-rootcause-20261006','execution_pattern':'one_shot','primary_result':'Causal comparison of retained source/XML and PDF glyph paths; no rerender','feedback_loop_required':False,'checkpoint_policy':'verified_only','scope':'Read retained P13 paragraph16 and neighbors/PDF/PNG; dedicated outputs only','inputs':bind,'budget':{'maximum_seconds':300,'api_usd':0,'model_calls':0,'rerenders':0},'acceptance':'Preserve exact facts/font/bbox/control count; distinguish inference/hypothesis/unresolved; source/PDF before after hashes equal','STOP':'Scope growth, missing byte inputs, proposed fix requires separate candidate task'};(O/'passport.json').write_text(json.dumps(passport,ensure_ascii=False,indent=2)+'\n')
normalize=lambda s:re.sub(r'\s+','',s).replace('\u00ad','');source=samples[0]['text'];actual=(I/'pdf-text.txt').read_text();checks=[('original_missing',normalize(source) in normalize(actual),False),('neighbor_present',normalize(samples[1]['text'])in normalize(actual),True),('fixture_missing',normalize(source)==normalize(source.replace('☐','',1)),False),('fixture_whitespace',normalize(source)==normalize(source.replace('  ','\n ')),True)];assert all(a==b for _,a,b in checks);(O/'gate-checks.json').write_text(json.dumps([{'case':n,'actual':a,'expected':b,'pass':a==b}for n,a,b in checks],indent=2)+'\n');(O/'SHA256SUMS').write_text(''.join(sha(p)+'  '+p.name+'\n'for p in sorted(O.iterdir())if p.is_file()and p.name!='SHA256SUMS'));print(result['status'],result['observed_fact'][-1])
