from pathlib import Path
import json,re,hashlib,shutil,subprocess,importlib.util
from datetime import datetime,timezone
WT=Path('/home/denis/projects/marzhavbetone.ru/.worktrees/codex-s1-legal-inputs-20261005'); OLD=WT/'tools/candidates/evidence/S1_LEGAL_INPUTS_20261005'; OUT=WT/'tools/candidates/evidence/S1_LEGAL_FOLLOWUP_20261005'; SRC=OUT/'sources'
now=datetime.now(timezone.utc).isoformat(); capture=SRC/'web-doc09-five-articles.capture.txt'; original_sha=hashlib.sha256(capture.read_bytes()).hexdigest(); capture.write_text('\n'.join(s.rstrip() for s in capture.read_text().splitlines()).rstrip()+'\n')
raw=capture.read_text(); rows=[]
for chunk in raw.split('\n--------------------------------------------------------------------------------\n'):
 url=re.search(r'\((https://www\.consultant\.ru/document/[^)]+)\)',chunk); heading=re.search(r'(ГК|АПК) РФ Статья ([0-9.]+)\. ',chunk)
 if not(url and heading): continue
 code,article=heading.groups(); article=article.rstrip('.'); key=('gk' if code=='ГК' else 'apk')+'-'+article.replace('.','-')
 lines=[s for s in chunk.splitlines() if re.match(r'^L\d+:',s)]
 start=next(i for i,s in enumerate(lines) if code+' РФ Статья '+article+'.' in s)
 end=next((i for i,s in enumerate(lines) if i>start and ('Комментарии к статье' in s or '[Button: Открыть полный текст документа]' in s)),len(lines))
 text='\n'.join(lines[start:end]).rstrip()+'\n'; file=SRC/('secondary-'+key+'.txt'); file.write_text(text)
 editions=re.findall(r'ред\. от \d{2}\.\d{2}\.\d{4}',chunk)
 rows.append({'source_id':key,'code':code+' РФ','article':article,'url':url.group(1),'source_class':'secondary','retrieved_at':now,'edition_as_displayed':editions,'edition_currentness':'NOT_VERIFIED','retrieval':'direct web open exact article URL; full captured legal body retained with line addresses','path':file.relative_to(WT).as_posix(),'sha256':hashlib.sha256(file.read_bytes()).hexdigest(),'capture_path':capture.relative_to(WT).as_posix(),'capture_sha256':hashlib.sha256(capture.read_bytes()).hexdigest(),'original_capture_sha256':original_sha,'captured_text_normalization':'trailing whitespace stripped; terminal newline','quote_obtained':True,'legal_acceptance':'NOT_PERFORMED','end_of_legal_body_observed':end<len(lines)})
assert sorted(s['source_id'] for s in rows)==['apk-110','apk-4','gk-309','gk-310','gk-711']
oldidx=json.loads((OLD/'buyer-claims-index.json').read_text()); oldsrc=json.loads((OLD/'sources/source-index.json').read_text()); row=next(d for d in oldidx['documents'] if d['path'].endswith('/09-pretenziya.docx'))
spec=importlib.util.spec_from_file_location('sem',WT/'tools/semantic_hash.py'); sem=importlib.util.module_from_spec(spec); spec.loader.exec_module(sem)
p=WT/row['path']; assert hashlib.sha256(p.read_bytes()).hexdigest()==row['file_sha256']; assert sem.semantic_hash(p)==row['semantic_hash']
shutil.copyfile(p,OUT/'doc09'/p.name); textsrc=WT/row['extracted_path']; shutil.copyfile(textsrc,OUT/'doc09'/textsrc.name)
for key in ['gk-395','gk-746']:
 old=next(s for s in oldsrc['sources'] if s['source_id']==key); rows.append(dict(old,reused_from_frozen_commit='dd0a85e43bf2fb8c3de42ede97c7c790db63d0a7',reuse_note='prior frozen source path; hash independently recomputed; not overwritten'))
 assert hashlib.sha256((WT/old['path']).read_bytes()).hexdigest()==old['sha256']
refs=json.loads((OLD/'literal-reference-map.json').read_text()); docrefs=[r for r in refs['references'] if r['document']==row['path']]; by={s['source_id']:s for s in rows}
for r in docrefs:
 assert r['proposed_norm_key'] in by,r
 r['source_id']=r['proposed_norm_key']; r['source_status']='SECONDARY_TEXT_OBTAINED_NOT_ACCEPTED'; r['source_sha256']=by[r['source_id']]['sha256']
index={'observed_at':now,'execution_pattern':'one_shot','primary_result':'S1_doc09_normative_input_followup','feedback_loop_required':False,'checkpoint_policy':'verified_only','source_sha':'a610c1524711f2179ba42c12f00692e4db7373a4','previous_frozen_input_commit':'dd0a85e43bf2fb8c3de42ede97c7c790db63d0a7','previous_frozen_not_modified':True,'document':dict(row,buyer_snapshot_path=(OUT/'doc09'/p.name).relative_to(WT).as_posix(),text_snapshot_path=(OUT/'doc09'/textsrc.name).relative_to(WT).as_posix()),'literal_reference_map':docrefs,'sources':rows,'preparation_status':'VERIFIED_NARROW_INPUT_09','legal_acceptance':'NOT_PERFORMED','currentness':'NOT_VERIFIED','existing_registry':'UNAVAILABLE; no new registry introduced','remaining_gates':['independent applicability/exceptions check','official effective-edition confirmation or existing version-specific human-review evidence','implicit legal mechanisms beyond literal references','hash-bound results and reread if wording corrected'],'source_route_policy':'No retries of prior blocked pravo routes; secondary direct article texts are working inputs only'}
(OUT/'doc09-index.json').write_text(json.dumps(index,ensure_ascii=False,indent=2)+'\n'); report=['# S1 — нормативный вход для узкой проверки файла 09','', '**VERIFIED_NARROW_INPUT_09 — подготовка выполнена; юридическая приёмка НЕ выполнена.**','', 'Зафиксирован полный фактический файл 09 и его извлечённый текст на принятом SHA `a610c1524711f2179ba42c12f00692e4db7373a4`. Доставлены прямыми URL недостающие тексты ГК 309/310/711 и АПК 4/110; предыдущие ГК 395/746 переиспользованы по проверенным SHA. Все семь буквальных статей файла 09 доступны эксперту локально.','', 'Старый frozen пакет `dd0a85e43bf2fb8c3de42ede97c7c790db63d0a7` не переписан. Новый индекс: `tools/candidates/evidence/S1_LEGAL_FOLLOWUP_20261005/doc09-index.json`. Он содержит byte/semantic hashes файла, URL/edition/date/source SHA, все восемь фрагментов с буквальными ссылками и карту источников.','', 'Все полученные статьи имеют source_class=secondary. Официальная действующая редакция, исключения и применимость не приняты. Предыдущие official PDF ВС находятся в прежнем пакете и также не дают автоматического currentness/PASS. Текст из вторичного источника допускает адресную подготовительную экспертизу, но не финальную нормативную приёмку.','', 'Эксперту: проверить утверждения фактического файла 09 о порядке и сроке претензии, обязанности оплатить принятые работы, процентов и продолжения начисления, выборе неустойки/процентов и судебных расходах; назвать исключения/условия применимости, не создавать новые нормы и не утверждать актуальность без доказательства редакции. Все выводы привязать к frozen semantic hash.','', 'Файл 10 остаётся в прежней принятой базе a610; обновление до следующей судовой правки разрешено только после подтверждённого merge координатором. Дополнительные источники файла 10 будут отдельным index, не overwrite этого snapshot.','', 'Проверка: exact 5 new source IDs, семь distinct literal norm keys joined, headings/article ends reviewed, all byte/text/source hashes verified; модельных/платных вызовов 0.']
(WT/'tools/candidates/MB001_S1_NORMATIVE_DOC09_FOLLOWUP_2026-10-05.md').write_text('\n'.join(report)+'\n')
manifest=OUT/'doc09-SHA256SUMS'; files=sorted(p for p in OUT.rglob('*') if p.is_file() and p!=manifest); manifest.write_text('\n'.join(hashlib.sha256(p.read_bytes()).hexdigest()+'  '+p.relative_to(WT).as_posix() for p in files)+'\n')
print(json.dumps({'status':index['preparation_status'],'document_sha256':row['file_sha256'],'document_semantic_hash':row['semantic_hash'],'distinct_literal_norms':sorted(set(r['proposed_norm_key'] for r in docrefs)),'new_sources':[(s['source_id'],s.get('end_of_legal_body_observed'),s['edition_as_displayed']) for s in rows[:5]],'source_count':len(rows),'claim_paragraphs':len(row['literal_claims']),'literal_ref_spans':row['literal_reference_count']},ensure_ascii=False,indent=2))
